package net.snowshock.goldentreasures.utils;

import cpw.mods.fml.common.ModMetadata;
import net.snowshock.goldentreasures.references.ReferencesModInfo;

public class MetadataHelper {
    public static ModMetadata transformMetadata(ModMetadata meta) {
        meta.authorList.clear();
        meta.authorList.add("LyraelRayne");
        meta.authorList.add("SnowShock35");
        meta.modId = ReferencesModInfo.MOD_ID;
        meta.name = ReferencesModInfo.MOD_NAME;
        meta.description = "The treasures of the long forgotten knights...";
        meta.version = ReferencesModInfo.VERSION;
        meta.url = "http://minecraft.curseforge.com/projects/Golden-Treasures";
        meta.credits = "x3n0ph0b3x & TrainerGuy22 for assets and base code from the discontinued mod Reliquary";
        mods.logoFile = "assets/goldentreasures/textures/items/golden_staff.png";
        meta.autogenerated = false;
        return meta;
    }
}
