package net.snowshock.goldentreasures.utils;

import cpw.mods.fml.common.ModMetadata;
import net.snowshock.goldentreasures.references.ReferencesModInfo;

public class MetadataHelper {
    public static ModMetadata transformMetadata(ModMetadata meta) {
        meta.authorList.clear();
        meta.authorList.add("SnowShock35");
        meta.modId = ReferencesModInfo.MOD_ID;
        meta.name = ReferencesModInfo.MOD_NAME;
        meta.description = "I'm a Description!";
        meta.version = ReferencesModInfo.VERSION;
        meta.url = "http://minecraft.curseforge.com/";
        meta.credits = "I'm some Credits";
        meta.autogenerated = false;
        return meta;
    }
}
